#ifndef DATA_VEHICLE_GENERIC_COMPONENTS_H
#define DATA_VEHICLE_GENERIC_COMPONENTS_H

#define DATA_VEHICLE_GENERIC_TYPES DataVehicleGeneric::LocalPosition,DataVehicleGeneric::LocalVelocity,DataVehicleGeneric::GlobalPosition,DataVehicleGeneric::GlobalVelocity

#endif // DATA_VEHICLE_GENERIC_COMPONENTS_H
