#ifndef MODULE_VEHICLE_MAVLINK_GLOBAL_H
#define MODULE_VEHICLE_MAVLINK_GLOBAL_H


#if defined(MODULE_VEHICLE_MAVLINK_LIBRARY)
#  define MODULE_VEHICLE_MAVLINKSHARED_EXPORT
#else
#  define MODULE_VEHICLE_MAVLINKSHARED_EXPORT
#endif

#endif // MODULE_VEHICLE_MAVLINK_GLOBAL_H
