#ifndef DATAVEHICLEMAVLINK_ALTITUDEREFERENCEFRAMES_H
#define DATAVEHICLEMAVLINK_ALTITUDEREFERENCEFRAMES_H

namespace DataVehicleMAVLINK
{

enum class AltitudeReferenceFrames
{
    AGL,
    ASL
};

}


#endif // DATAVEHICLEMAVLINK_ALTITUDEREFERENCEFRAMES_H
