#ifndef DATA_VEHICLE_MAVLINK_COMPONENTS_H
#define DATA_VEHICLE_MAVLINK_COMPONENTS_H

#define DATA_VEHICLE_MAVLINK_TYPES DataMAVLINK::GPSStatus

#include "Components/gps_status.h"

namespace DataVehicleMAVLINK
{

}

#endif // DATA_VEHICLE_MAVLINK_COMPONENTS_H
