#ifndef DATA_VEHICLE_MAVLINK_COMPONENTS_H
#define DATA_VEHICLE_MAVLINK_COMPONENTS_H

#define DATA_VEHICLE_MAVLINK_TYPES DataMAVLINK::EmptyMAVLINK

#include "empty_mavlink.h"


#endif // DATA_VEHICLE_MAVLINK_COMPONENTS_H
