#ifndef MODULE_MAVLINK_COMMS_GLOBAL_H
#define MODULE_MAVLINK_COMMS_GLOBAL_H

#ifdef _MSC_VER
#  if defined(MODULE_MAVLINK_COMMS_LIBRARY)
#    define MODULE_MAVLINK_COMMSSHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_MAVLINK_COMMSSHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_MAVLINK_COMMSSHARED_EXPORT
#endif

#endif // MODULE_MAVLINK_COMMS_GLOBAL_H
