#ifndef MODULE_GROUND_STATION_GLOBAL_H
#define MODULE_GROUND_STATION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_GROUND_STATION_LIBRARY)
#  define MODULE_GROUND_STATIONSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_GROUND_STATIONSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_GROUND_STATION_GLOBAL_H
