#ifndef MODULE_RTA_NASAPHASE2_GLOBAL_H
#define MODULE_RTA_NASAPHASE2_GLOBAL_H


#ifdef _MSC_VER
#  if defined(MODULE_RTA_NASAPHASE2_LIBRARY)
#    define MODULE_RTA_NASAPHASE2SHARED_EXPORT  __declspec(dllexport)
#  else
#    define MODULE_RTA_NASAPHASE2SHARED_EXPORT  __declspec(dllimport)
#  endif
#else
#  define MODULE_RTA_NASAPHASE2SHARED_EXPORT
#endif


#endif // MODULE_RTA_NASAPHASE2_GLOBAL_H
