#ifndef MODULE_RTA_NASAPHASE2_GLOBAL_H
#define MODULE_RTA_NASAPHASE2_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(MODULE_RTA_NASAPHASE2_LIBRARY)
#  define MODULE_RTA_NASAPHASE2SHARED_EXPORT Q_DECL_EXPORT
#else
#  define MODULE_RTA_NASAPHASE2SHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // MODULE_RTA_NASAPHASE2_GLOBAL_H
